# Generated by Django 3.1.7 on 2021-04-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlpapp', '0003_career_internship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
    ]
