# Generated by Django 3.1.7 on 2021-04-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlpapp', '0004_delete_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('detail', models.CharField(max_length=20)),
                ('appoint', models.TextField()),
            ],
        ),
    ]
